theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-memocarb.jpg'
    footer: '/assets/images/logo-memocarb.jpg'
  home:
    head:
      title: site